apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
spec:
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
        - name: go-server
          image: go-server-img
          imagePullPolicy: Never
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-server
spec:
  type: NodePort
  selector:
    app: go-server
  ports:
    - port: 8080
      nodePort: 30007
