version: 2.1

workflows:
  build_and_test:
    jobs:
      - kubernetes

jobs:
  kubernetes:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Initialize cluster
          command: |
            bash -x scripts/init_k8s_cluster.sh
            NODE=$HOSTNAME bash -x scripts/wait_for_node.sh            

      - run:
          name: Build go-server image
          command: |
            make
            sudo docker build . -t go-server-img

      - run:
          name: Deploy go-server in cluster
          command: |
            kubectl apply -f deployment.yaml
            POD=go-server bash -x scripts/wait_for_pod.sh

      - run:
          name: Integration test(s)
          command: |
            curl $HOSTNAME:30007
