version: 2.1

workflows:
  build_and_test:
    jobs:
      - kubernetes

jobs:
  kubernetes:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Initialize cluster
          command: |
            bash -x scripts/init_k8s_cluster.sh

      - run:
          name: Wait for cluster
          command: |
            NODE=$HOSTNAME bash -x scripts/wait_for_node.sh
